# permissions for end users to view middlewares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: goma-operator
    app.kubernetes.io/managed-by: kustomize
  name: middleware-viewer-role
rules:
- apiGroups:
  - gomaproj.github.io
  resources:
  - middlewares
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gomaproj.github.io
  resources:
  - middlewares/status
  verbs:
  - get
